apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app.service.name }}
spec:
    type: {{ .Values.app.service.type }} # LoadBalancer, NodePort, ClusterIP
    selector:
        tag: {{ .Values.app.deploy.tag }}
    ports:
        - port: {{ .Values.app.service.port }} 
          targetPort: {{ .Values.app.service.targetPort }} 
          {{- if eq .Values.app.service.type "NodePort" }}
          nodePort: {{ .Values.app.service.nodePort }}
          {{- end }}          
