apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.deploy.name}}
  labels:
    tag: {{.Values.app.deploy.tag}}
spec:
  replicas: {{.Values.app.deploy.replicas}}
  strategy:
    type: {{.Values.app.deploy.strategy.type}}
  selector:
    matchLabels:
      tag: {{.Values.app.deploy.tag}}
  template:
    metadata:
      labels:
        tag: {{.Values.app.deploy.tag}}
    spec:
      containers:
        - name: {{.Values.app.deploy.container.name}}
          image: {{.Values.app.deploy.container.image}}
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_VERSION
              value: 2022-11-20.1
            {{- range $k, $v := .Values.app.env_vars }}
            - name: {{ quote $k }}    
              value: {{ quote $v }}           
            {{- end }}                
          # envFrom:
          #   - configMapRef:
          #       name: my-app-cm
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '64Mi'
              cpu: '200m'
            limits:
              memory: '128Mi'
              cpu: '500m'
