apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    role: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: my-app
      tier: web
  template:
    metadata:
      labels:
        role: my-app
        tier: web
    spec:
      containers:
      - name: my-app
        image: my_app:v1.0.0
        imagePullPolicy: Never        
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"