apiVersion: v1
kind: Service
metadata:
  name: my-test
spec:
  type: LoadBalancer
  selector:
    role: my-test  
  ports:
  - port: 8080          # ServicePort.
    targetPort: 8080    # If targetPort not specifed it will be same as ServicePort.
