###
POST http://localhost:3000/api/user/create
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password123",
    "username": "username"  ,
    "roles":["ADMIN", "USER"]  
}
### WRONG CREDENTIALS
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "test@test.com",  
    "password": "password12311"
}
### LOGIN GOOD CREDENTIALS
POST http://localhost:3000/api/user/login
my-app-trace-id: 1234
Content-Type: application/json

{
    "email": "admin@test.com", 
    "password": "password123"    

}
###
GET http://localhost:3000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7Im5hbWUiOiJzYW1wbGUgdXNlcm5hbWUiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJwYXNzd29yZCI6IiIsInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjMyZmFjM2Q1ZjcwODFjNGNiMmI0MWJkIiwiY3JlYXRlZEF0IjoiMjAyMi0wOS0yNVQwMToxNzo0OS40MzBaIiwidXBkYXRlZEF0IjoiMjAyMi0wOS0yNVQwMToxNzo0OS40MzBaIiwiX192IjowfSwiaWF0IjoxNjY0MDY4NjY5LCJleHAiOjE2NjQxNTUwNjl9.sOkeVjb3_611h7zfvtiVhkwUZYSaM0At7QfagLr5ulY

###
GET http://localhost:3000/api/user/findAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7Im5hbWUiOiJzYW1wbGUgdXNlcm5hbWUiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJwYXNzd29yZCI6IiIsInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjMyZmFjM2Q1ZjcwODFjNGNiMmI0MWJkIiwiY3JlYXRlZEF0IjoiMjAyMi0wOS0yNVQwMToxNzo0OS40MzBaIiwidXBkYXRlZEF0IjoiMjAyMi0wOS0yNVQwMToxNzo0OS40MzBaIiwiX192IjowfSwiaWF0IjoxNjY0MDY4NjY5LCJleHAiOjE2NjQxNTUwNjl9.sOkeVjb3_611h7zfvtiVhkwUZYSaM0At7QfagLr5ulY






