---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQxMjM=
  mongodb-password: c2VjcmV0cGFzc3dvcmQxMjM=
  mongodb-replica-set-key: cmVwbGljYWtleQ==